name: Hello World!

on:
    push:
        branches:
            - main

jobs:
    hello_world_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Say hello
              run: |
                  echo "Hello World!"
    date_job:
        runs-on: ubuntu-20.04
        steps:
            -name: Show Date
            run: |
                date
    directory_content_job:
        runs-on: ubuntu-20.04
        steps:
            -name: show directory content
            run: |
                ls
